### ISSUE TITLE
Cannot find module ../lib/docs

### ISSUE THREAD

**Issue by john-boy** [strongloop/strong-docs#118]
# Description/Steps to reproduce
After installing strong-docs and attempting to generate documentation I received a message that the module lib/docs could not be found.  There is no module lib/docs in the installation package.

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by alimohyudin** [comment]
Found any solution?

**Comment by raymondfeng** [comment]
@john-boy @alimohyudin Which version do you use? I just tried `strong-docs@4.2.0` and it has `lib/docs.js` there.
