### ISSUE TITLE
Link Checking

### ISSUE THREAD

**Issue by ritch** [strongloop/strong-docs#21]
It would be nice to be able to run `sdocs --check-links` and have all your links checked against two tests:
1. If it is a local anchor, does the anchor exist?
2. If it is an absolute URL, does the URL respond with a status code < 400?

**Comment by dhmlau** [comment]
@raymondfeng @bajtos , trying to close issues that have been inactive for a long time.  Since the last comment was in 2013, do we still need this?  Thanks.

**Comment by bajtos** [comment]
I am ok to close this issue as stale.
