### ISSUE TITLE
Display built-in model properties from JSON definitions

### ISSUE THREAD

**Issue by crandmck** [strongloop/strong-docs#56]
Built-in model properties are now defined in JSON files (eg. https://github.com/strongloop/loopback/blob/master/common/models/application.json).  Would like strong-docs to render these properties into a table in API docs using this JSON rather than us needing to put them in JSdoc comments. There's even a `description` property that's basically the documentation for eacg property.

**Comment by dhmlau** [comment]
Since we are focusing on LB4 which has GA'ed, I don't think we'll have the bandwidth to get this done in a reasonable timeframe.  Closing this ticket.
