### ISSUE TITLE
Nav list is not proper HTML

### ISSUE THREAD

**Issue by crandmck** [strongloop/strong-docs#60]
Per https://gist.github.com/williamle8300/9a39df7ac573df549d39 the HTML (ul / li) generated for the navigation  may not be entirely valid.  Need to confirm.

**Comment by dhmlau** [comment]
Since we are focusing on LB4 which has GA'ed, I don't think we'll have the bandwidth to get this done in a reasonable timeframe.  Closing this ticket.
