### ISSUE TITLE
Allow static assets to be mounted to the same path

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/strong-docs#7]
For example, we have the following files:

/a/1.md
/a/1.png

1.md has a link to 1.png.

I would like to have /a/1.png to be mounted to /a/1.png so that I don't have to change 1.md for the link to 1.png.

**Comment by dhmlau** [comment]
@raymondfeng @bajtos , trying to close issues that have been inactive for a long time.  Since the last comment was in 2013, do we still need this?  Thanks.
