### ISSUE TITLE
Open up this repo

### ISSUE THREAD

**Issue by ritch** [strongloop/strong-docs#77]
This has been on the un-official backlog for years. Let's use Rand's talk @ node interactive as an excuse to get it opened up.

We need to remove the top header templating from the library since it hardcodes the StrongLoop logo / name. Allowing a custom header / company name to be provided. Otherwise there is already approval to open up this by moving it to the `strongloop` github org.

@hacksparrow @crandmck

**Comment by crandmck** [comment]
The repo is now public. Closing this.
