### ISSUE TITLE
TypeScript: Support @example, markdown processing, and syntax highlighting

### ISSUE THREAD

**Issue by mpatsute** [strongloop/strong-docs#80]
TypeScript: Support @example, markdown processing, and syntax highlighting.
connects to strongloop-internal/scrum-asteroid#219

**Comment by bajtos** [comment]
I run into this issue while working on https://github.com/strongloop/loopback-next/pull/391.

 - Only the first paragraph is shown, everything after the first empty line is discarded.
 - `@example` annotation is not recognized, it is rendered as plaintext `@example` in the output.
